<a href="https://colab.research.google.com/github/Nebiat-Zemikeal/New/blob/main/CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np
from matplotlib import pyplot as plt
from tensorflow.keras import layers, callbacks, utils, datasets, models
from tensorflow.keras.models import Sequential

# Set a random seed to maintain similar values
np.random.seed(42)

In [2]:
# Load data from keras
# x = inputs and y = outputs

(x_train, y_train), (x_test, y_test) = datasets.mnist.load_data()

# Numerical operations (e.g. CNNs) prefer values between 0, 1 or -1, 1
# We must scale the values from 255 (default inputs) to 0-1 (CNN inputs)
# Note that we also convert the arrays to float32,
#   this could be float16/float8 for speed or float64 for accuracy, etc
x_train = x_train.astype("float32") / 255
x_test = x_test.astype("float32") / 255

# Conv2D-nets require 4D inputs: batch, row, col, color
# Unfortunately, MNIST does not provide a color dimension: it's greysca
# Therefore, we add the color dimensions to represent greyscale
COLOR_DIM = -1
x_train = np.expand_dims(x_train, axis=COLOR_DIM)
x_test = np.expand_dims(x_test, axis=COLOR_DIM)

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [3]:
num_classes = np.unique(y_train).__len__()  # 10
img_shape = x_train[0].shape  # 28, 28, 1

In [4]:
print("Sample of labels before one-hot encoding")
print(np.random.choice(y_train.ravel(), size=5))

# tf.keras function to transform integer labels to one-hot encodings
y_train = utils.to_categorical(y_train, num_classes)
y_test = utils.to_categorical(y_test, num_classes)

print("Sample of labels after one-hot encoding")
print(y_train[np.random.choice(range(y_train.shape[0]), size=5)])

Sample of labels before one-hot encoding
[4 0 0 8 3]
Sample of labels after one-hot encoding
[[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [5]:
print("Confirm Shape")
print(f"x_train shape: {x_train.shape}")  # (60000, 28, 28, 1)
print(f"x_test shape : {x_test.shape}")  # (10000, 28, 28, 1)

print("Confirm Samples")
print(f"train samples: {x_train.shape[0]}")  # 60000
print(f"test samples : {x_test.shape[0]}")  # 10000

print("Confirm Train Range")
print(f"x_train min: {x_train.min()}")  # 0.0
print(f"x_train max: {x_train.max()}")  # 1.0

print("Confirm Test Range")
print(f"x_test min: {x_test.min()}")  # 0.0
print(f"x_test max: {x_test.max()}")  # 1.0

Confirm Shape
x_train shape: (60000, 28, 28, 1)
x_test shape : (10000, 28, 28, 1)
Confirm Samples
train samples: 60000
test samples : 10000
Confirm Train Range
x_train min: 0.0
x_train max: 1.0
Confirm Test Range
x_test min: 0.0
x_test max: 1.0


In [6]:
print("Confirm Shape")
print(f"y_train shape: {y_train.shape}")  # (60000, 10)
print(f"y_test shape : {y_test.shape}")  # (10000, 10)

print("Confirm Samples")
print(f"train samples: {y_train.shape[0]}")  # 60000
print(f"test samples : {y_test.shape[0]}")  # 10000

print("Confirm Train Range")
print(f"y_train min: {y_train.min()}")  # 0.0
print(f"y_train max: {y_train.max()}")  # 1.0

print("Confirm Test Range")
print(f"y_test min: {y_test.min()}")  # 0.0
print(f"y_test max: {y_test.max()}")  # 1.0

Confirm Shape
y_train shape: (60000, 10)
y_test shape : (10000, 10)
Confirm Samples
train samples: 60000
test samples : 10000
Confirm Train Range
y_train min: 0.0
y_train max: 1.0
Confirm Test Range
y_test min: 0.0
y_test max: 1.0


In [11]:
# Define the layers for the model
input_layer = layers.Input(shape=img_shape)
hidden_layer1 = layers.Conv2D(32, kernel_size=(3, 3), activation="relu")
hidden_layer2 = layers.MaxPooling2D(pool_size=(2, 2))
hidden_layer3 = layers.Conv2D(64, kernel_size=(3, 3), activation="relu")
hidden_layer4 = layers.MaxPooling2D(pool_size=(2, 2))
hidden_layer5 = layers.Flatten()
hidden_layer6 = layers.Dropout(0.5)
output_layer = layers.Dense(num_classes, activation="softmax")

# Build the Sequential model
model = Sequential([
    input_layer,
    hidden_layer1,
    hidden_layer2,
    hidden_layer3,
    hidden_layer4,
    hidden_layer5,
    hidden_layer6,
    output_layer
])

In [14]:
# Define how we will build the model
model = models.Sequential(name='MNIST_CNN_Tutorial')

# Create the input layer to understand the shape of each image and batch-size
model.add(
    layers.Input(
        shape=img_shape,
        # batch_size=batch_size,
        name='Image_Batch_Input_Layer',
    )
)

# Add the firest convolution layer with 32 filters
model.add(
    layers.Conv2D(
        filters=nfilters_hidden1,
        kernel_size=kernel_shape,
        activation=activation,
        padding=padding,
        strides=strides,
        name='First_Conv2D_Layer'
    )
)

# Reduce the dimensionality after the first Conv-layer w/ MaxPool2D
model.add(
    layers.MaxPooling2D(
        pool_size=pool_shape,
        name="First_MaxPool2D_Layer"
    )
)

# Add the firest convolution layer with 64 filters
model.add(
    layers.Conv2D(
        filters=nfilters_hidden2,
        kernel_size=kernel_shape,
        activation=activation,
        padding=padding,
        strides=strides,
        name='Second_Conv2D_Layer'
    )
)

# Reduce the dimensionality after the second Conv-layer w/ MaxPool2D
model.add(
    layers.MaxPooling2D(
        pool_size=pool_shape,
        name="Second_MaxPool2D_Layer"
    )
)

# Convert the 2D outputs to a 1-D vector in preparation for label prediction
model.add(
    layers.Flatten(
        name="Flatten_from_Conv2D_to_Dense"
    )
)

# Dropout 50% of the neurons from the Conv+Flatten layers to regulate
model.add(
    layers.Dropout(
        rate=dropout_rate,
        name="Dropout_from_Dense_to_Output"
    )
)

# Compute the weighted-logistic for each possible label in one-hot encoding
model.add(
    layers.Dense(
        units=num_classes,
        activation="softmax",
        name="n-Dimensional_Logistic_Output_Layer"
    )
)

In [15]:
# Define model parameters
nfilters_hidden1 = 32
nfilters_hidden2 = 64
kernel_shape = (3, 3)
activation = "relu"
padding = "valid"
strides = (1, 1)
pool_shape = (2, 2)
dropout_rate = 0.5

In [16]:
Model: "MNIST_CNN_Tutorial"

In [17]:
model.compile(
    loss="categorical_crossentropy",
    optimizer="adam",
    metrics=["accuracy"]
)


In [20]:
# Import Modules
from tensorflow.keras import layers, utils, datasets, models
import numpy as np # Added numpy import

# Load Data
(x_train, y_train), (x_test, y_test) = datasets.mnist.load_data()

# Preprocess data
x_train, x_test = preprocess(x_train, x_test)

# Encode labels
y_train, y_test = one_hot_encoding(y_train, y_test)

# Create Model
img_shape = x_train[0].shape # Get img_shape after preprocessing
num_classes = np.unique(y_train.argmax(axis=1)).__len__() # Get num_classes from one-hot encoded labels
model = create_cnn_model(img_shape, num_classes)

# Compile Model
model.compile(
    loss="categorical_crossentropy",
    optimizer="adam",
    metrics=["accuracy"]
)

In [21]:
def preprocess(x_train, x_test):
    """Scales and reshapes the image data."""
    x_train = x_train.astype("float32") / 255
    x_test = x_test.astype("float32") / 255
    COLOR_DIM = -1
    x_train = np.expand_dims(x_train, axis=COLOR_DIM)
    x_test = np.expand_dims(x_test, axis=COLOR_DIM)
    return x_train, x_test

def one_hot_encoding(y_train, y_test):
    """Converts integer labels to one-hot encoded labels."""
    num_classes = np.unique(y_train).__len__()
    y_train = utils.to_categorical(y_train, num_classes)
    y_test = utils.to_categorical(y_test, num_classes)
    return y_train, y_test

def create_cnn_model(img_shape, num_classes):
    """Creates and returns a CNN model."""
    # Define model parameters (assuming these are already defined in the notebook)
    nfilters_hidden1 = 32
    nfilters_hidden2 = 64
    kernel_shape = (3, 3)
    activation = "relu"
    padding = "valid"
    strides = (1, 1)
    pool_shape = (2, 2)
    dropout_rate = 0.5

    model = models.Sequential(name='MNIST_CNN_Tutorial')

    model.add(layers.Input(shape=img_shape, name='Image_Batch_Input_Layer'))

    model.add(layers.Conv2D(filters=nfilters_hidden1, kernel_size=kernel_shape, activation=activation, padding=padding, strides=strides, name='First_Conv2D_Layer'))
    model.add(layers.MaxPooling2D(pool_size=pool_shape, name="First_MaxPool2D_Layer"))

    model.add(layers.Conv2D(filters=nfilters_hidden2, kernel_size=kernel_shape, activation=activation, padding=padding, strides=strides, name='Second_Conv2D_Layer'))
    model.add(layers.MaxPooling2D(pool_size=pool_shape, name="Second_MaxPool2D_Layer"))

    model.add(layers.Flatten(name="Flatten_from_Conv2D_to_Dense"))
    model.add(layers.Dropout(rate=dropout_rate, name="Dropout_from_Dense_to_Output"))
    model.add(layers.Dense(units=num_classes, activation="softmax", name="n-Dimensional_Logistic_Output_Layer"))

    return model

In [23]:
# Fit Model
model.fit(x_train, y_train, epochs=10, batch_size=32, validation_split=0.1)

# Evaluate Model
loss, accuracy = model.evaluate(x_test, y_test)
print(f"Test Loss: {loss}, Test Accuracy: {accuracy}")

Epoch 1/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 42s 24ms/step - accuracy: 0.8514 - loss: 0.4798 - val_accuracy: 0.9835 - val_loss: 0.0567
Epoch 2/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 40s 24ms/step - accuracy: 0.9712 - loss: 0.0916 - val_accuracy: 0.9883 - val_loss: 0.0432
Epoch 3/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 42s 24ms/step - accuracy: 0.9781 - loss: 0.0683 - val_accuracy: 0.9898 - val_loss: 0.0374
Epoch 4/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 40s 24ms/step - accuracy: 0.9818 - loss: 0.0581 - val_accuracy: 0.9907 - val_loss: 0.0326
Epoch 5/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 41s 23ms/step - accuracy: 0.9841 - loss: 0.0508 - val_accuracy: 0.9933 - val_loss: 0.0299
Epoch 6/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 40s 23ms/step - accuracy: 0.9865 - loss: 0.0433 - val_accuracy: 0.9902 - val_loss: 0.0336
Epoch 7/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 40s 23ms/step - accuracy: 0.9876 - loss: 0.0425 - val_accuracy: 0.9920 - val_loss: 0.0319
Epoch 8/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 42s 24ms/step - accuracy: 0.9880 -

In [24]:
epochs = 5  # How many iterations should we cycle over the entire MNIST dataset
validation_split = 0.1  # how many images to hold out per epoch: 10%
batch_size = 128  # nominal use cases: 32, 64, 128, 256, 512
early_stopping = callbacks.EarlyStopping(patience=5)

history = model.fit(
    x=x_train,
    y=y_train,
    batch_size=batch_size,
    epochs=epochs,
    validation_split=validation_split,
    callbacks=[early_stopping]
)

Epoch 1/5
422/422 ━━━━━━━━━━━━━━━━━━━━ 36s 85ms/step - accuracy: 0.9902 - loss: 0.0294 - val_accuracy: 0.9930 - val_loss: 0.0303
Epoch 2/5
422/422 ━━━━━━━━━━━━━━━━━━━━ 36s 86ms/step - accuracy: 0.9920 - loss: 0.0251 - val_accuracy: 0.9928 - val_loss: 0.0292
Epoch 3/5
422/422 ━━━━━━━━━━━━━━━━━━━━ 36s 86ms/step - accuracy: 0.9929 - loss: 0.0225 - val_accuracy: 0.9932 - val_loss: 0.0289
Epoch 4/5
422/422 ━━━━━━━━━━━━━━━━━━━━ 35s 83ms/step - accuracy: 0.9924 - loss: 0.0241 - val_accuracy: 0.9925 - val_loss: 0.0274
Epoch 5/5
422/422 ━━━━━━━━━━━━━━━━━━━━ 42s 85ms/step - accuracy: 0.9929 - loss: 0.0214 - val_accuracy: 0.9928 - val_loss: 0.0280


In [25]:
# The results below may differ from the table above because of randomised
#  initial conditions and randomised processes during fitting: e.g., `Dropout`
for key, val in history.history.items():
    print(f'{key:>12}: {np.round(val, 3)}')

    accuracy: [0.991 0.992 0.993 0.993 0.993]
        loss: [0.027 0.025 0.023 0.023 0.023]
val_accuracy: [0.993 0.993 0.993 0.993 0.993]
    val_loss: [0.03  0.029 0.029 0.027 0.028]


In [26]:
test_score = model.evaluate(x_test, y_test, verbose=0)
train_score = model.evaluate(x_train, y_train, verbose=0)

In [27]:
print(f"{'     Test loss'}: {test_score[0]}")
print(f"{'    Train loss'}: {train_score[0]}")
print()
print(f"{' Test accuracy'}: {test_score[1]}")
print(f"{'Train accuracy'}: {train_score[1]}")

     Test loss: 0.0208812914788723
    Train loss: 0.010287669487297535

 Test accuracy: 0.9927999973297119
Train accuracy: 0.9971333146095276


In [30]:
print(f"Test loss: {test_score[0]:.5f}")
print(f"Train loss: {train_score[0]:.5f}")
print()
print(f"Test accuracy: {test_score[1]:.2%}")
print(f"Train accuracy: {train_score[1]:.2%}")

Test loss: 0.02088
Train loss: 0.01029

Test accuracy: 99.28%
Train accuracy: 99.71%


In [32]:
pred_test = model.predict(x_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step


In [33]:
plot_samples(
    images=x_test,
    labels=y_test,
    predictions=pred_test,
    n_rows=7,
    n_cols=7,
    figsize=(8, 8)
)

NameError: name 'plot_samples' is not defined

In [35]:
def plot_samples(images, labels, predictions=None, n_rows=5, n_cols=5, figsize=(10, 10)):
    """Plots sample images with their labels and optional predictions."""
    plt.figure(figsize=figsize)
    for i in range(n_rows * n_cols):
        plt.subplot(n_rows, n_cols, i + 1)
        plt.imshow(images[i].squeeze(), cmap='gray')
        if predictions is not None:
            predicted_label = np.argmax(predictions[i])
            true_label = np.argmax(labels[i])
            color = 'green' if predicted_label == true_label else 'red'
            plt.title(f"True: {true_label}\nPred: {predicted_label}", color=color)
        else:
            true_label = np.argmax(labels[i])
            plt.title(f"True: {true_label}")
        plt.axis("off")
    plt.tight_layout()
    plt.show()

In [36]:
"""
# This is the expected properties for MNIST
num_classes = 10  # 0, 1, 2, 3, 4, 5, 6, 7, 8, 9
img_shape = 28, 28, 1  # 28 rows, 28 columns, 1 color -- grayscale
"""

# load data from keras
# x = inputs and y = outputs

dataset = 'mnist'  # 'mnist'  # 'fashion_mnist'  # 'cifar10'
if dataset == 'mnist':
    (x_train, y_train), (x_test, y_test) = datasets.mnist.load_data()
if dataset == 'fashion_mnist':
    (x_train, y_train), (x_test, y_test) = datasets.fashion_mnist.load_data()
if dataset == 'cifar10':
    (x_train, y_train), (x_test, y_test) = datasets.cifar10.load_data()

# Numerical operatoins (e.g. CNNs) prefer values between 0, 1 or -1, 1
# We must scale the values from 255 (default inputs) to 0-1 (CNN inputs)
# Note that we also convert the arrays to float32,
#   this could be float16/float8 for speed for float64 for accuracy, etc
x_train = x_train.astype("float32") / 255
x_test = x_test.astype("float32") / 255

# Conv2D-nets require 4D inputs: batch, row, col, color
if np.ndim(x_train) == 3: # no color dimension
    # Add the color dimensions to represent greyscale
    COLOR_DIM = -1
    x_train = np.expand_dims(x_train, axis=COLOR_DIM)
    x_test = np.expand_dims(x_test, axis=COLOR_DIM)
